CREATE TABLE IF NOT EXISTS crime_records (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    crime_id VARCHAR(40) NOT NULL UNIQUE,
    police_station VARCHAR(120) NOT NULL,
    district VARCHAR(120) NOT NULL,
    crime_type VARCHAR(120) NOT NULL,
    crime_date DATE NOT NULL,
    crime_time TIME NULL,
    victim VARCHAR(160) NULL,
    suspect VARCHAR(160) NULL,
    vehicle VARCHAR(120) NULL,
    weapon VARCHAR(120) NULL,
    latitude DECIMAL(9, 6) NOT NULL,
    longitude DECIMAL(9, 6) NOT NULL,
    location POINT GENERATED ALWAYS AS (ST_SRID(POINT(longitude, latitude), 4326)) STORED NOT NULL,
    status VARCHAR(40) NOT NULL,
    notes TEXT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CHECK (latitude BETWEEN 11.0 AND 19.5),
    CHECK (longitude BETWEEN 74.0 AND 79.5),
    SPATIAL INDEX idx_crime_records_location (location),
    INDEX idx_crime_records_district (district),
    INDEX idx_crime_records_station (police_station),
    INDEX idx_crime_records_type (crime_type),
    INDEX idx_crime_records_date (crime_date),
    INDEX idx_crime_records_status (status),
    INDEX idx_crime_records_suspect (suspect)
);
