"""Optional LLM adapters for natural-language to SQL conversion."""

from __future__ import annotations

import json
import os
from dataclasses import dataclass, field
from typing import Protocol
from urllib import request


SCHEMA_CONTEXT = """
You are an assistant for Karnataka SCRB investigators.
Convert the investigator's question into one safe SQL SELECT query.

Database table:
crime_records(
  crime_id, police_station, district, crime_type, crime_date, crime_time,
  victim, suspect, vehicle, weapon, latitude, longitude, status, notes
)

Rules:
- Return only SQL.
- Use only SELECT statements.
- Use the table crime_records.
- Never use INSERT, UPDATE, DELETE, DROP, ALTER, TRUNCATE, CREATE, or GRANT.
- Prefer COUNT(*) for "how many" questions.
- Use district names stored in the database, for example:
  Bengaluru Urban, Mysuru, Dharwad.
- For map or hotspot questions include latitude and longitude.
"""


@dataclass(frozen=True)
class SqlPlan:
    """SQL generated by a rule or LLM."""

    sql: str
    params: dict[str, object] = field(default_factory=dict)


class LLMProvider(Protocol):
    """Provider interface for LLM-generated SQL."""

    name: str

    def generate_sql(self, question: str) -> SqlPlan:
        """Generate a SQL query for a question."""


class NoOpProvider:
    """Fallback provider used when no LLM is configured."""

    name = "offline-fallback"

    def generate_sql(self, question: str) -> SqlPlan:
        return SqlPlan(
            sql=(
                "SELECT crime_id, district, police_station, crime_type, crime_date, "
                "crime_time, status FROM crime_records "
                "ORDER BY crime_date DESC LIMIT 20"
            )
        )


class OpenAIProvider:
    """OpenAI adapter. Requires OPENAI_API_KEY and the openai package."""

    name = "openai"

    def __init__(self, model: str | None = None) -> None:
        self.model = model or os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

    def generate_sql(self, question: str) -> SqlPlan:
        from openai import OpenAI

        client = OpenAI()
        response = client.responses.create(
            model=self.model,
            input=f"{SCHEMA_CONTEXT}\nQuestion: {question}\nSQL:",
        )
        return SqlPlan(sql=response.output_text.strip())


class GeminiProvider:
    """Gemini adapter. Requires GEMINI_API_KEY and google-generativeai."""

    name = "gemini"

    def __init__(self, model: str | None = None) -> None:
        self.model = model or os.getenv("GEMINI_MODEL", "gemini-1.5-flash")

    def generate_sql(self, question: str) -> SqlPlan:
        import google.generativeai as genai

        genai.configure(api_key=os.environ["GEMINI_API_KEY"])
        model = genai.GenerativeModel(self.model)
        response = model.generate_content(f"{SCHEMA_CONTEXT}\nQuestion: {question}\nSQL:")
        return SqlPlan(sql=response.text.strip())


class OllamaProvider:
    """Local Ollama adapter. Requires Ollama running on localhost."""

    name = "ollama"

    def __init__(self, model: str | None = None, url: str | None = None) -> None:
        self.model = model or os.getenv("OLLAMA_MODEL", "llama3.1")
        self.url = url or os.getenv("OLLAMA_URL", "http://localhost:11434/api/generate")

    def generate_sql(self, question: str) -> SqlPlan:
        payload = {
            "model": self.model,
            "prompt": f"{SCHEMA_CONTEXT}\nQuestion: {question}\nSQL:",
            "stream": False,
        }
        data = json.dumps(payload).encode("utf-8")
        req = request.Request(self.url, data=data, headers={"Content-Type": "application/json"})
        with request.urlopen(req, timeout=60) as response:
            body = json.loads(response.read().decode("utf-8"))
        return SqlPlan(sql=body["response"].strip())


def build_llm_provider() -> LLMProvider:
    """Build the configured LLM provider.

    Set AI_PROVIDER to one of: openai, gemini, ollama, none.
    """

    provider = os.getenv("AI_PROVIDER", "none").lower()

    if provider == "openai":
        return OpenAIProvider()
    if provider == "gemini":
        return GeminiProvider()
    if provider == "ollama":
        return OllamaProvider()
    return NoOpProvider()
